apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaderboards-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaderboards
  template:
    metadata:
      labels:
        app: leaderboards
    spec:
      containers:
        - name: leaderboards
          image: rsoteam8/leaderboards:1.0.0-SNAPSHOT-13.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: leaderboards
spec:
  type: ClusterIP
  ports:
    - port: 8085
      protocol: TCP
      targetPort: server
  selector:
    app: leaderboards

